version: "3.9"
services:
  server:
    container_name: server
    build: 
      context: .
      dockerfile: ServerDockerfile
    ports:
      - 8000:8000
  auth_server:
    container_name: auth_server
    build: 
      context: .
      dockerfile: AuthDockerfile
    ports:
      - 8500:8500