name: Inference Service Unit Testing and Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  REPO_NAME: ${{secrets.DOCKERHUB_REPO}}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pycodestyle
        run: |
          pycodestyle src/server src/auth test
      - name: Test with pytest
        run: |
          PYTHONPATH=./:./src/server pytest test

  push-image-to-docker-hub:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    - name: Build the Docker auth image
      run: docker build . --file AuthDockerfile --tag $DOCKER_USER/$REPO_NAME:auth_server
    - name: Build the Docker server image
      run: docker build . --file ServerDockerfile --tag $DOCKER_USER/$REPO_NAME:server
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:auth_server
    - name: Docker Push
      run: docker push $DOCKER_USER/$REPO_NAME:server